### ISSUE TITLE
permutation p-values should never be zero

### ISSUE THREAD

**Issue by slowkow** [statlab/permute#108]
I noticed a p-value of zero on this page: https://statlab.github.io/permute/user/one-sample.html

Consider using the more conservative

`p_u = (hits + 1) / (reps + 1)`

instead of

`p = hits / reps`

> The valid but conservative p-value `p_u` has been recommended by a number of authors including Davison and Hinkley (1997), Manly (1997) and Ernst (2004). The extent to which `p_u` over-estimates the exact p-value depends on `m_t`.
> https://www.ncbi.nlm.nih.gov/pubmed/21044043

**Comment by pbstark** [comment]
I agree that we should make this change.

But my reasons are slightly different. I don't see any reason to avoid 0 nor to bias the estimate: historically, I've used confidence bounds to take care of that. I think the resulting quantity, (hits+1)/(tries + 1) is a generally conservative _randomized_ P-value, not an exact P-value (as Phipson & Smyth wrote). They condition on the orbit of the data _and_ on the realized random elements of the group. I think it is more natural to condition only on the orbit of the data, since re-running the test typically will give a different P-value from the same data.

**Comment by pbstark** [comment]
The new version offers two options: count the original data as one of the permutations (then the p-value is never zero, and the p-value is in fact an exact p-value for a randomized test), or don't (in which case the p-value is an estimated p-value, and the estimate can be zero).
