### ISSUE TITLE
Error in "hits = np.sum(dist >= tst)" in one_sample test

### ISSUE THREAD

**Issue by UdiBhaskar** [statlab/permute#156]
in the https://github.com/statlab/permute/blob/2ff8f4861fea44ef412ebc6a5304b7570bd6c66c/permute/core.py#L607 `dist` is list and we can't compare a list like that, it will give an error. [#155](https://github.com/statlab/permute/pull/155) pull request may solve this error. You will get the error only if `keep_dist=True` in the one_sample.

**Comment by pbstark** [comment]
Dear Uday Bhaskar--

Thank you for looking at the code and reporting this issue. The underlying problem is slightly different: it has to do with how 2-tailed tests are handled, which ignored the fact that the test statistic has a discrete distribution. The "tails" branch fixes this, but there have been technical issues merging it into the master branch relating to AppVeyor and TravisCI. We are currently moving everything to Python 3 from Python 2. I expect we will be able to merge the tails branch within a few days, which will fix this problem.

Again, I'm very grateful for the bug report and for your help!

Philip
