### ISSUE TITLE
Reshape nsgk

### ISSUE THREAD

**Issue by kellieotto** [statlab/permute#54]
1st dimension should be the 183 domain. 2nd dimension should be the video. Then rater, timestamp (to match input matrix for irr)

**Comment by jarrodmillman** [comment]
Naomi says the videos don't all have the same number of time stamps.

Numbers as follows:

Video 1: 36
Video 2: 32
Video 3: 35
Video 4: 37
Video 5: 31
Video 6: 35
Video 7: 40
Video 8: 32

**Comment by jarrodmillman** [comment]
The way we have the data structured now is is going to result in artificially large concordances in videos with less than 40 timestamps.  The columns which come after the end of the real timestamps look like the raters have perfect concordance because they're just all 0s.

Seems like this should be an easy fix.  In pseudocode,

data = matrix for a particular category
timestamps_per_video = [36, 32, etc...]
for i in range(timestamps_per_video):
    truncated = data[i, :, :timestamps_per_video[i] ]
    simulate_ts_dist(truncated)

- Kellie

**Comment by kellieotto** [comment]
Make a JSON file for the data instead?
